#!/bin/bash

# if an environment variable WADS is set, search for WADs in that directory
MYWADS=${WADS:-$HOME/Downloads/Doom/WADs}

ENGINE=gzdoom

function print_help {
	echo "Usage: doomlist [OPTION]... [WADNAME]"
	echo "	If no options are specified, list .wad and .pk3 files in MYWADS"
	echo "	If an env var WADS is set, MYWADS is set to WADS instead of the default"
	echo
	echo "	WADNAME        load WADNAME into gzdoom and play"
	echo "	-a FILE        add FILE to the MYWADS directory"
	echo "	-d PATH        search for Doom wads in PATH instead of default"
	echo "	-D ENGINEPATH  use doom engine executable at PATH instead of default"
	echo "	-l             list information about files in MYWADS directory"
	echo "	-L OPTIONS     list information about files in MYWADS directory"
	echo "	                   with options OPTIONS (do not include leading hyphen)"
	echo "	-r FILE        remove FILE from the MYWADS directory"
	echo "	-h             display this message"
	exit 1
}

function list_wads {
	wadlist=$(find $MYWADS \( -iname *.wad -o -iname *.pk3 \) \! -iname DOOM* -printf "%f\n" | sort)

	printf "%-17s %-17s %-17s %-17s\n" $(echo $wadlist)
}

if [ $# -eq 0 ]
then
	list_wads
	exit
fi

while getopts "a:d:D:lL:hr:" OPT
do
	case "$OPT" in
		a)
			cp -v $OPTARG $MYWADS
			exit
			;;
		d)	
			MYWADS=$OPTARG
			;;
		D)	
			ENGINE=$(realpath $OPTARG)
			;;
		l)
			ls -l $MYWADS
			exit
			;;
		L)
			ls -l -$OPTARG $MYWADS
			exit
			;;
		r)
			rm -v $MYWADS/$OPTARG
			exit
			;;
		h)
			print_help
			exit 1
			;;
		*)
			print_help
			exit 1
			;;	
	esac
done
shift $((OPTIND - 1))

if [ -z "$1" ]
then
	list_wads
	exit
fi

WAD=$MYWADS/$1*

if [ -e $WAD ]
then
	"$ENGINE" $WAD
else
	echo "$1 not found in $MYWADS"
fi
