#!/bin/bash

MYWADS=$HOME/Downloads/Doom/WADs

function print_help {
	echo "Usage: doomlist [OPTION] [WADNAME]"
	echo "    If no options are specified, list .wad and .pk3 files in MYWADS"
	echo "    WADNAME       load WADNAME into gzdoom and play\n"
	echo "    -a FILE       add FILE to the MYWADS directory"
	echo "    -r FILE       remove FILE from the MYWADS directory"
	echo "    -h            display this message"
	exit 1
}

if [ $# -eq 0 ] 
then
	wadlist=$(find $MYWADS \( -iname *.wad -o -iname *.pk3 \) \! -iname DOOM* -printf "%f\n" | sort)

	printf "%-17s %-17s %-17s %-17s\n" $(echo $wadlist)
	exit
fi

while getopts "a:hr:" OPT
do
	case "$OPT" in
		a)
			cp -v $OPTARG $MYWADS
			exit
			;;
		r)
			rm -v $MYWADS/$OPTARG
			exit
			;;
		h)
			print_help
			exit 1
			;;
		*)
			print_help
			exit 1
			;;	
	esac
done
shift $((OPTIND - 1))

if [ -e $MYWADS/$1 ]
then
	gzdoom $MYWADS/$1
else
	echo "$1 not found in $MYWADS"
fi
