#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
    echo 'wav-to-mp3 -i [input.wav] -o [directory]'
    exit 1
fi

input_file=
output_dir=

while getopts "i:o:" opt; do
    case "$opt" in
        i)
            input_file="$OPTARG"
            if [[ ! ( "$input_file" =~ .*\.wav ) ]]; then
                echo >&2 "must be a wav file"
                exit 1
            fi
            ;;
        o)
            output_dir="$OPTARG"
            if [ ! -d "$output_dir" ]; then
                echo >&2 "-o must be a directory"
                exit 1
            fi
            ;;
        h)
            echo 'wav-to-mp3 -i [input.wav] -o [output_dir]'
            ;;
        *)
            echo >&2 "unrecognized option $OPTARG"
            exit 1
    esac 
done

if [ -z "$input_file" ]; then
    echo >&2 "no input file specified"
    exit 1
fi

if [ -z "$output_dir" ]; then
    echo >&2 "no output directory specified"
    exit 1
fi

filename=${input_file%.*}

ffmpeg -i "${input_file}" -vn -ar 44100 -ac 2 -b:a 320k "${output_dir:?no output directory specified}/${filename}.mp3"
